feat: updated dependencies
erento/nestjs-modules pull request #42
Opened 2022-02-14 10:23 UTC by janmaleserento

2022-02-15 15:35 UTC, rokerkony requested changes

2022-02-16 08:58 UTC, janmaleserento commented on modules/google-pubsub/package.json
> +    "@nestjs/common": "^8.0.0",
I thought it might be safer for future use, but I don't really have a preference here. I'm up for `>=`.

2022-02-16 08:58 UTC, janmaleserento commented on modules/common/package.json
> +    "@nestjs/core": "^8.0.0",
> I thought it might be safer for future use, but I don't really have a preference here. I'm up for `>=`.

2022-02-16 08:58 UTC, janmaleserento commented on modules/common/package.json
>      "typescript": ">=3.9.9"
missed this one, with all the refactoring, thank you 👍

2022-03-07 09:49 UTC, merged